apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k8s-app: automium-cluster-autoscaler
  name: cluster-autoscaler-config
  namespace: kube-system
data:
  cloudprovider.yaml: |-
{{ .Values.cloudProviderConfig | toYaml | indent 4 }}
