{{- $dot := . }}
{{- with .Values.ingresspool }}
{{- if .enabled }}
apiVersion: core.automium.io/v1beta1
kind: Service
metadata:
  labels:
    app: kubernetes-nodepool
    helm.sh/chart: {{ include "automium-cluster.chart" $dot }}
    app.kubernetes.io/component: {{ include "automium-cluster.name" $dot }}
    app.kubernetes.io/part-of: {{ include "automium-cluster.fullname" $dot }}
    app.kubernetes.io/managed-by: {{ $dot.Release.Service }}
  name: {{ .name | trunc 63 | trimSuffix "-" }}
spec:
  env:
  - name: cluster_name
    value: {{ include "serviceName" $dot }}
  - name: kubeadm_custom
    value: |-
      kubeletExtraArgs:
        kube-reserved: cpu=300m,memory=0.5Gi,ephemeral-storage=1Gi
        system-reserved: cpu=200m,memory=0.2Gi,ephemeral-storage=1Gi
        eviction-hard: memory.available<200Mi,nodefs.available<10%
  - name: network_security_ports
    value: "80,443"
  extra: []
  {{- if eq $dot.Values.provider "entercloudsuite" }}
  flavor: {{ include "ecsFlavor" . }}
  {{- else }}
  flavor: "not implemented"
  {{- end }}
  replicas: {{ .replicas }}
  tags: []
  version: v{{ include "serviceVersion" $dot.Values.version }}
---
{{- end }}
{{- end }}
